# Helper module for 011_modules.py. Do not edit this file.

DEG_TO_RAD = 3.141592653589793 / 180.0
RAD_TO_DEG = 180.0 / 3.141592653589793


def to_radians(deg):
    return deg * DEG_TO_RAD


def to_degrees(rad):
    return rad * RAD_TO_DEG
